server:
  port: 9020

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/VastseaLee/configurationfile    # 配置git仓库的地址
          search-paths: demo,common,gateway,authserver                        # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: VastseaLee                                            # git仓库的账号（私有库必填）
          password: Liwangyang02                                             # git仓库的密码（私有库必填）                                          # git仓库的密码（私有库必填）
      label: master

eureka:
  instance:
    prefer-ip-address: true
  client:
    #表示是否将自己注册到Eureka Server，默认为true。
    register-with-eureka: true
    #表示是否从Eureka Server获取注册信息，默认为true。
    fetch-registry: true
    service-url:
      #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
      defaultZone: http://lwy:950202@192.168.0.25:9000/eureka/
